### ISSUE TITLE
Python problem ?

### ISSUE THREAD

**Issue by sidskeg** [SignalsEverywhere/gr-dect2#7]
Hi
Just tried running the GRC part and the following error appeared ;

 File "/usr/local/lib/python2.7/dist-packages/dect2/console.py", line 27, in <module>
    from PyQt4 import QtCore, QtGui
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
 
Any help gratefully received

**Comment by KR0SIV** [comment]
Have you run the GRC file in gnuradio first or are you trying to execute the python file directly?

**Comment by sidskeg** [comment]
Hi
Downloaded everything from here, following the video, opened gnuradio, then opened the dect2.grc file and ran it. Then the error codes appeared.
I'm using kali-liux 2
Cheers

**Comment by sidskeg** [comment]
Full error log is :

Loading: "/root/gr-dect2/grc/dect2.grc"
>>> Done

Generating: '/root/gr-dect2/grc/top_block.py'

Executing: /usr/bin/python2 -u /root/gr-dect2/grc/top_block.py

Traceback (most recent call last):
  File "/root/gr-dect2/grc/top_block.py", line 35, in <module>
    import dect2
  File "/usr/local/lib/python2.7/dist-packages/dect2/__init__.py", line 46, in <module>
    from console import *
  File "/usr/local/lib/python2.7/dist-packages/dect2/console.py", line 27, in <module>
    from PyQt4 import QtCore, QtGui
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

**Comment by git-minix** [comment]
similar issue with dect2_Hackrf.grc:
$ ./top_block.py 
Warning: failed to XInitThreads()
Traceback (most recent call last):
  File "./top_block.py", line 31, in <module>
    import dect2
  File "/usr/local/lib/python2.7/dist-packages/dect2/__init__.py", line 46, in <module>
    from console import *
  File "/usr/local/lib/python2.7/dist-packages/dect2/console.py", line 27, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class

**Comment by git-minix** [comment]
If I use this hint from ttps://github.com/pavelyazev/gr-dect2/issues/10

```
git clone git://github.com/pavelyazev/gr-dect2.git
cd gr-dect2/
# Below one switches to the older QT4 branch:
git checkout pyqt4  
mkdir build
cd build
cmake ../
make
sudo make install
sudo ldconfig
```

the PyQt5 RuntimeError disappear  and I get
```
$ ./top_block.py 
linux; GNU C++ version 6.3.0 20170221; Boost_106200; UHD_003.009.005-0-unknown

gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.10
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy soapy redpitaya 
Using HackRF One with firmware 2018.01.1 
gr::log :INFO: audio source - Audio sink arch: alsa
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x142
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x6a00010
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x6a00011

```

**Comment by xscode** [comment]
I managed to sort this by converting the code to pyQT5.  Change the file /usr/local/lib/python2.7/dist-packages/dect2/console.py to the one in my repo at 
https://github.com/xscode/misc_scripts/blob/master/console.py

**Comment by rems78** [comment]
HEllo,
I use the modified console.py from xscode. Same issue, same error message.
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
ubuntu 18.04 ; GNU Radio Companion 3.7.11
If anybody could help.
Regards
